Transact/Transact.Web/Areas/AppUser/ViewModels/TransactionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Transact.Models;
using Transact.Web.Utils;
using Transact.Web.ViewModels;

namespace Transact.Web.Areas.AppUser.ViewModels
{
    public class TransactionViewModel
    {
        public long Id { get; set; }

        public long SenderAccountId { get; set; }

        public string SenderAccountNumber { get; set; }

        public string SenderAccountNickName { get; set; }

        public string SenderClientName { get; set; }

        public string ReceiverAccountNickName { get; set; }

        public string ReceiverClientName { get; set; }

        public long StatusId { get; set; }

        public IList<AccountViewModel> AllAvailableAccounts { get; set; }

        public long ReceiverAccountId { get; set; }

        [Required(ErrorMessage = "You must choose Receiver Account#")]
        [StringLength(10, MinimumLength = 10)]        
        public string ReceiverAccountNumber { get; set; }

        [MaxLength(35)]
        public string Description { get; set; }

        [Range(0, Double.PositiveInfinity)]
        public decimal Amount { get; set; }

        public DateTime TimeStamp { get; set; }

        public string StatusName { get; set; }

        public TransactionIOStatus IOstatus { get; set; }

        public AccountViewModel PreSelectedAccount { get; set; }
    }
}

Transact/Transact.Web/Areas/AppUser/Controllers/TransactionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Transact.Models.Dtos;
using Transact.Services.Contracts;
using Transact.Web.Areas.AppUser.ViewModels;
using Transact.Web.Mapper.Contracts;
using Transact.Web.Utills;

namespace Transact.Web.Areas.AppUser.Controllers
{
    [Area("AppUser")]
    [CustomAuthorize("User")]
    public class TransactionController : Controller
    {
        private readonly IUserServices userServices;
        private readonly IAccountServices accountServices;
        private readonly ITransactionServices transactionServices;
        private readonly IAuthorizationManager authorizationManager;
        private readonly IHttpContextAccessor contextAccessor;
        private readonly ITransactionVeiwModelMapper transactionMapper;
        private readonly IAccountViewModelMapper accountMapper;

        public TransactionController(
            IUserServices userServices,
            IAccountServices accountServices,
            IAccountViewModelMapper accountMapper,
            ITransactionServices transactionServices,
            IAuthorizationManager authorizationManager,
            IHttpContextAccessor contextAccessor,
            ITransactionVeiwModelMapper transactionMapper)
        {
            this.transactionMapper = transactionMapper;
            this.userServices = userServices;
            this.accountServices = accountServices;
            this.accountMapper = accountMapper;
            this.transactionServices = transactionServices;
            this.authorizationManager = authorizationManager;
            this.contextAccessor = contextAccessor;
        }

        [HttpGet]
        public async Task<IActionResult> AddTransaction(long? preSelectedAccount)
        {            
             var currentUserId = authorizationManager.GetLoggedUserId();
             var allUserAccounts = await accountServices.GetAllUserAvailableAccountsAsync(currentUserId);

             var allMappedUserAccounts = accountMapper.MapFrom(allUserAccounts);

             var viewModel = new TransactionViewModel()
             {
                 AllAvailableAccounts = allMappedUserAccounts,

             };

             if (preSelectedAccount != null)
             {
                 var mappedAccount = allMappedUserAccounts.FirstOrDefault(x => x.Id == preSelectedAccount);
                 viewModel.PreSelectedAccount = mappedAccount;
                 viewModel.SenderAccountId = mappedAccount.Id;
             }

             return View(viewModel);                                  
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditTransaction(long transactionId)
        {          
            var currentUserId = authorizationManager.GetLoggedUserId();
            var allUserAccounts = await accountServices.GetAllUserAvailableAccountsAsync(currentUserId);

            var allMappedUserAccounts = accountMapper.MapFrom(allUserAccounts);
           
            var transactionToEdit = await transactionServices.GetSingleTransactionForEditingAsync(transactionId);
           
            var viewModel = transactionMapper.MapFrom(transactionToEdit);
            viewModel.AllAvailableAccounts = new List<AccountViewModel>(allMappedUserAccounts);
           
            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> ListTransactions(long preSelectedAccount)
        {
            var currentUserId = authorizationManager.GetLoggedUserId();
            var allUserAccounts = await accountServices.GetAllUserAvailableAccountsAsync(currentUserId);

            List<TransactionDto> fiveSelectedTransactions;
            List<TransactionViewModel> mappedFiveTransactions;
            int totalPages;

            var allMappedUserAccounts = accountMapper.MapFrom(allUserAccounts);

            var viewModel = new ListTransactionsViewModel()
            {
                AllAvailableAccounts = new List<AccountViewModel>(allMappedUserAccounts)
            };

            totalPages = await transactionServices
                .GetPageCountForTransactionsAsync(5, preSelectedAccount, null);

            viewModel.PreSelectedAccount = allMappedUserAccounts
                 .SingleOrDefault(x => x.Id == preSelectedAccount);

            if (preSelectedAccount > 0)
            {
                fiveSelectedTransactions = new List<TransactionDto>(await transactionServices
                  .GetFiveTransactionsForAccountDescAsync(
                  1, preSelectedAccount, currentUserId));

                mappedFiveTransactions = new List<TransactionViewModel>(transactionMapper.MapFromWithAccount(fiveSelectedTransactions, preSelectedAccount));
            }
            else
            {
                mappedFiveTransactions = new List<TransactionViewModel>();
            }

            viewModel.FiveTransactionsList = new FiveTransactionListViewModel()
            {
                FiveSelectedTransactions = new List<TransactionViewModel>(mappedFiveTransactions),
                CurrPage = 1
            };

            if (totalPages > 1)
            {
                viewModel.FiveTransactionsList.NextPage = 2;
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> GetFiveTransactions(int currPage, long preSelectedAccount)
        {
            var currentUserId = authorizationManager.GetLoggedUserId();

            if (currPage == 0)
            {
                currPage = 1;
            }          
           
            var currentNewPage = currPage;         
     
             List<TransactionDto> fiveSelectedTransactions;
             List<TransactionViewModel> mappedFiveTransactions;
             int totalPages;
            
             var allUserAccounts = await accountServices.GetAllUserAvailableAccountsAsync(currentUserId);
   
             totalPages = await transactionServices.GetPageCountForTransactionsAsync(
                 5,
                 preSelectedAccount,
                 null);
            
             if (totalPages == 1 || totalPages <= currentNewPage)
             {
                 currentNewPage = totalPages;
             }
            
            
             fiveSelectedTransactions = new List<TransactionDto>(await transactionServices
                 .GetFiveTransactionsForAccountDescAsync(
                 currentNewPage, 
                 preSelectedAccount,
                 currentUserId));
            
             mappedFiveTransactions = new List<TransactionViewModel>(transactionMapper.MapFromWithAccount(fiveSelectedTransactions, preSelectedAccount));
                    
            
             var viewModel = new FiveTransactionListViewModel()
             {
                 FiveSelectedTransactions = mappedFiveTransactions,
                 CurrPage = currentNewPage
             };
            
             if (totalPages > currentNewPage)
             {
                 viewModel.NextPage = currentNewPage + 1;                
             }
            
             if (currentNewPage > 1)
             {
                 viewModel.PrevPage = currentNewPage - 1;
             }               
            
             return PartialView("_FiveTransactionsPartial", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveTransaction(TransactionViewModel transactionToSave)
        {          
              if (!ModelState.IsValid)
              {
                  return BadRequest("Please submit valid form!");
              }
          
              var transactionDto = transactionMapper.MapFrom(transactionToSave);
          
              var result = await transactionServices.SaveTransactionAsync(transactionDto);
          
              return Ok($"Transaction #{result.Id} for: {result.Amount}bgn was SAVED succesfully!");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateTransaction(TransactionViewModel transactionToSave)
        {
              if (!ModelState.IsValid)
              {
                  return BadRequest("Please submit valid form!");
              }
             
              var transactionDto = transactionMapper.MapFrom(transactionToSave);
             
              var result = await transactionServices.UpdateTransactionAsync(transactionDto);
             
              return Ok($"Transaction #{result.Id} for: {result.Amount}bgn was UPDATED succesfully!");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SendUpdatedTransaction(TransactionViewModel transactionToSave)
        {
             if (!ModelState.IsValid)
             {
                 return BadRequest("Please submit valid form!");
             }

             var transactionDto = transactionMapper.MapFrom(transactionToSave);

             var result = await transactionServices.SendUpdatedTransactionAsync(transactionDto);

             return Ok($"Transaction #{result.Id} for: {result.Amount}bgn was UPDATED and SENT succesfully!");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SendTransaction(long transactionId)
        {
              if (!ModelState.IsValid)
              {
                  return BadRequest("Please submit valid form!");
              }

              var result = await transactionServices.SendTransactionAsync(transactionId);


Transact/Transact.Web/Areas/AppUser/Views/Transaction/AddTransaction.cshtml
@model TransactionViewModel
@{
    ViewData["Title"] = "Add Transaction";
    Layout = "~/Areas/AppUser/Views/Shared/_LayoutCustom.cshtml";
}

<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-autocomplete/1.0.7/jquery.auto-complete.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
<link href="~/css/transaction-select2-style.css" rel="stylesheet" />

<div class="page-content">
    <div class="container">
        <div class="content-area card">
            <div class="card-innr card-innr-fix2">
                <div class="card-head">
                    <h6 class="card-title">Add Transaction</h6>
                </div>
                <div class="gaps-1x"></div><!-- .gaps -->
                <form asp-controller="Transaction" asp-action="SaveTransaction" id="submit-transaction-form" class="row">
                    <div class="col-md-6">
                        <div class="input-item input-with-label">
                            <label class="input-item-label">Select Account to send Money From:</label>
                            <div>
                                <select class="input-bordered" asp-for="SenderAccountId" id="sender-account-selector">
                                    @if (Model.PreSelectedAccount != null)
                                    {
                                        <option value="@Model.PreSelectedAccount.Id" selected disabled hidden>@Model.PreSelectedAccount.NickName</option>
                                    }
                                    else
                                    {
                                        <option value="" selected disabled hidden></option>
                                    }

                                    @foreach (var account in Model.AllAvailableAccounts)
                                    {
                                        <option bal="@account.Balance" att="@account.ClientName" value="@account.Id">@account.NickName</option>
                                    }
                                </select>
                                <span asp-validation-for="SenderAccountId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="input-item input-with-label col-md-8" id="sender-client-name-div">
                            @if (Model.PreSelectedAccount != null)
                            {
                            <span>Client: </span>@Model.PreSelectedAccount.ClientName
                            }
                        </div>
                        <div class="input-item input-with-label">
                            <label class="input-item-label">Description:</label>
                            <input asp-for="Description" class="input-bordered" type="text" placeholder="Must be up to 35 characters">
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="input-item input-with-label">
                            <label for="auto" class="input-item-label">Find Receiver Account:</label>
                            <input asp-for="ReceiverAccountNumber" class="input-bordered" id="input-for-receiver-account" type="text" placeholder="Live Search by Account Number" />
                            <span asp-validation-for="ReceiverAccountNumber" id="message" class="text-danger"></span>
                        </div>
                        <div class="input-item input-with-label col-md-8" id="receiver-client-name-div"></div>
                        <div class="input-item input-with-label">
                            <label class="input-item-label">Amount:</label>
                            <input asp-for="Amount" class="input-bordered" type="number" id="transaction-amount-selector" placeholder="Please enter valid amount">
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-lg-offset-0">
                        <div>
                            <div class="input-item input-with-label">
                                <span class="col-6 col-lg-3">
                                    <input type="submit" class="btn btn-warning-alt" id="save-transaction-button" value="Save Transaction" />
                                </span>
                                <span class="col-6 col-lg-3">
                                    <input type="submit" class="btn btn-primary-alt" id="send-transaction-button" value="Send Transaction" />
                                </span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div><!-- .card -->

    </div><!-- .container -->
</div><!-- .page-content -->

@section Scripts{

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-autocomplete/1.0.7/jquery.auto-complete.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

    <script src="~/js/find-accounts-jquery-select2-version.js"></script>
    <script src="~/js/adding-transactions-ajax.js"></script>
    <script src="~/js/sender-accounts-select2.js"></script>
    <script src="~/js/receiver-accounts-settings.js"></script>
}


Transact/Transact.Web/Areas/AppUser/Views/Transaction/EditTransaction.cshtml
@model TransactionViewModel
@{
    ViewData["Title"] = "Add Transaction";
    Layout = "~/Areas/AppUser/Views/Shared/_LayoutCustom.cshtml";
}

<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-autocomplete/1.0.7/jquery.auto-complete.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
<link href="~/css/transaction-select2-style.css" rel="stylesheet" />

<div class="page-content">
    <div class="container">
        <div class="content-area card">
            <div class="card-innr card-innr-fix2">
                <div class="card-head">
                    <h6 class="card-title">Add Transaction</h6>
                </div>
                <div class="gaps-1x"></div><!-- .gaps -->
                <form asp-controller="Transaction" asp-action="SaveTransaction" id="edit-transaction-form" class="row">
                    <div class="col-md-6">
                        <input type="hidden" class="input-bordered" asp-for="Id" value="@Model.Id">
                        <div class="input-item input-with-label">
                            <label class="input-item-label">Select Account to send Money From:</label>
                            <div>
                                <select class="input-bordered" asp-for="SenderAccountId" id="sender-account-selector">
                                    <option value="" selected disabled hidden></option>
                                    @foreach (var account in Model.AllAvailableAccounts)
                                    {
                                        <option bal="@account.Balance" att="@account.ClientName" value="@account.Id">@account.NickName</option>
                                    }
                                </select>
                                <span asp-validation-for="SenderAccountId" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="input-item input-with-label col-md-8" id="sender-client-name-div">
                            <div>Client Name: @Model.SenderClientName</div>
                        </div>


                        <div class="input-item input-with-label">
                            <label class="input-item-label">Description:</label>
                            <input asp-for="Description" class="input-bordered" value="@Model.Description" type="text" placeholder="Must be up to 35 characters">
                            <span asp-validation-for="Description" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="input-item input-with-label">
                            <label for="auto" class="input-item-label">Find Receiver Account:</label>
                            <input asp-for="ReceiverAccountNumber" class="input-bordered" value="@Model.ReceiverAccountNumber" id="input-for-receiver-account" type="text" placeholder="Live Search by Account Number" />
                            <span asp-validation-for="ReceiverAccountNumber" id="message" class="text-danger"></span>
                        </div>
                        <div class="input-item input-with-label col-md-8" id="receiver-client-name-div">
                            <div>Client Name: @Model.ReceiverClientName</div>
                        </div>
                        <div class="input-item input-with-label">
                            <label class="input-item-label">Amount:</label>
                            <input asp-for="Amount" class="input-bordered" value="@Model.Amount" type="number" id="transaction-amount-selector" min="1" placeholder="Please enter valid amount">
                            <span asp-validation-for="Amount" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="col-lg-offset-0">
                        <div>
                            <div class="input-item input-with-label">
                                <span class="col-6 col-lg-3">
                                    <input type="submit" class="btn btn-warning-alt" id="update-transaction-button" value="Update Transaction" />
                                </span>
                                <span class="col-6 col-lg-3">
                                    <input type="submit" class="btn btn-primary-alt" id="send-updated-transaction-button" value="Send Transaction" />
                                </span>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div><!-- .card -->

    </div><!-- .container -->
</div><!-- .page-content -->

@section Scripts{

    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-autocomplete/1.0.7/jquery.auto-complete.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>

    <script src="~/js/find-accounts-jquery-select2-version.js"></script>
    <script src="~/js/sender-accounts-select2.js"></script>
    <script src="~/js/receiver-accounts-settings.js"></script>

    <script src="~/js/editing-transactions-ajax.js"></script>
}




Transact/Transact.Web/Areas/AppUser/Views/Transaction/ListTransactions.cshtml
@model ListTransactionsViewModel
@{
    ViewData["Title"] = "ListTransactions";
    Layout = "~/Areas/AppUser/Views/Shared/_LayoutCustom.cshtml";
}

<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
<link href="~/css/transaction-select2-style.css" rel="stylesheet" />
<link href="~/css/custom-empty-transactions.css" rel="stylesheet" />

<div class="page-content">
    <div class="container">
        <div class="card content-area">
            <div class="card-innr">
                <div class="input-item input-with-label col-md-4 " style="float: right;">
                    <label class="input-item-label">Account selected:</label>
                    <div>
                        <select id="transactions-account-selector" class="input-bordered" asp-for="PreSelectedAccount">
                            <option accid="default" selected disabled hidden>Select account</option>
                            @*<option accid="default">No Account Selected</option>*@
                            @foreach (var account in Model.AllAvailableAccounts)
                            {
                                <option bal="@account.Balance" accid="@account.Id" value="@account.Id">@account.NickName</option>
                            }
                        </select>
                        <span asp-validation-for="PreSelectedAccount" class="text-danger"></span>
                    </div>
                </div>
                <div class="card-head">
                    <h4 class="card-title">Transactions by Date</h4>
                </div>
                <div id="target-transaction-list-table">
                    @await Html.PartialAsync("_FiveTransactionsPartial", Model.FiveTransactionsList)
                </div>
            </div><!-- .card-innr -->
        </div><!-- .card -->
    </div><!-- .container -->
</div><!-- .page-content -->

@section Scripts{

    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/js/select2.min.js"></script>
    <script src="/js/manage-transactions-pagination-table-buttons.js"></script>
    <script src="~/js/transaction-action-buttons-from-listing.js"></script>
    <script src="/assets/js/script.js?ver=104"></script>
    
}