Transact/Transact.Web/Areas/Admin/ViewModels/AddClientsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Transact.Web.Areas.Admin.ViewModels
{
    public class AddClientsViewModel
    {
        public ClientViewModel ClientForm { get; set; }

        public ClientListViewModel ClientsList { get; set; }
    }
}

Transact/Transact.Web/Areas/Admin/ViewModels/ClientViewModel.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using Transact.Models;

namespace Transact.Web.Areas.Admin.ViewModels
{
    public class ClientViewModel
    {
        public long Id { get; set; }

        [Required]
        [MinLength(3)]
        [MaxLength(35)]
        public string Name { get; set; }

        public int NumberOfAccounts { get; set; }

        public ICollection<Account> Accounts { get; set; }

        public ICollection<UsersClients> UsersClients { get; set; }
    }
}

Transact/Transact.Web/Areas/Admin/ViewModels/ManageClientViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Transact.Web.Areas.Admin.ViewModels
{
    public class ManageClientViewModel
    {
        public ClientViewModel ClientToManage { get; set; }
        public ManageClientAccountsViewModel ManageClientAccounts { get; set; }
    }
}

Transact/Transact.Web/Areas/AppUser/ViewModels/ClientViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Transact.Web.Areas.AppUser.ViewModels
{
    public class ClientViewModel
    {
        public long Id { get; set; }

        [Required]
        [MinLength(3)]
        [MaxLength(35)]
        public string Name { get; set; }

        public ICollection<AccountViewModel> Accounts { get; set; }
    }
}

Transact/Transact.Web/Areas/Admin/Controllers/ClientController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Transact.Services.Contracts;
using Transact.Web.Areas.Admin.ViewModels;
using Transact.Web.Mapper.Contracts;
using Transact.Web.Utills;

namespace Transact.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [CustomAuthorize("Admin")]
    public class ClientController : Controller
    {
        private readonly IClientServices clientServices;
        private readonly IAccountServices accountServices;
        private readonly IAccountViewModelMapper accountMapper;
        private readonly IClientViewModelMapper clientMapper;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly IUserServices userServices;
        private readonly IUserViewModelMapper userMapper;
        private readonly IConfiguration configuration;

        public ClientController(
            IClientServices clientServices, 
            IAccountServices accountServices, 
            IAccountViewModelMapper accountMapper,
            IClientViewModelMapper clientMapper, 
            IHttpContextAccessor httpContextAccessor, 
            IUserServices userServices, 
            IUserViewModelMapper userMapper,
            IConfiguration configuration)
        {
            this.clientServices = clientServices;
            this.accountServices = accountServices;
            this.accountMapper = accountMapper;
            this.clientMapper = clientMapper;
            this.httpContextAccessor = httpContextAccessor;
            this.userServices = userServices;
            this.userMapper = userMapper;
            this.configuration = configuration;
        }

        [HttpGet]
        public async Task<IActionResult> AddClient()
        {
                var fiveClientsById = await clientServices.GetFiveClientsByIdAsync(1);
                var mappedFiveClientsById = clientMapper.MapFrom(fiveClientsById);
                var totalPages = await clientServices.GetPageCountForClientsAsync(5);

                var viewModel = new AddClientsViewModel()
                {
                    ClientForm = new ClientViewModel(),
                    ClientsList = new ClientListViewModel()
                    {
                        CurrPage = 1,
                        TotalPages = totalPages,
                        FiveClientsById = mappedFiveClientsById
                    }
                };

                if (totalPages > 1)
                {
                    viewModel.ClientsList.NextPage = 2;
                }

                return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> SaveClient(AddClientsViewModel manageViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("Please submit valid form!");
            }

            var clientDto = clientMapper.MapFrom(manageViewModel.ClientForm);

            var client = await clientServices.AddClientAsync(clientDto);

            return Ok($"Client with name: \"{client.Name}\" addedd succesfully!");
            
        }

        [HttpGet]
        public async Task<IActionResult> GetFiveClientsById(int? currPage)
        {
           if (!ModelState.IsValid)
           {
               return BadRequest();
           }

           var currentPage = currPage ?? 1;

           var totalPages = await clientServices.GetPageCountForClientsAsync(5);
           var fiveClientsById = await clientServices.GetFiveClientsByIdAsync(currentPage);
           var mappedFiveClientsById = clientMapper.MapFrom(fiveClientsById);


           var viewModel = new ClientListViewModel()
           {
               CurrPage = currentPage,
               TotalPages = totalPages,
               FiveClientsById = mappedFiveClientsById
           };

           if (totalPages > currentPage)
           {
               viewModel.NextPage = currentPage + 1;
           }

           if (currentPage > 1)
           {
               viewModel.PrevPage = currentPage - 1;
           }

           return PartialView("_ClientListTable", viewModel);
          
        }

        [HttpGet]
        public async Task<IActionResult> ManageAccountsForClient(long clientId)
        {
            var currentPage = 1;

            var fiveAccountsDtos = await accountServices.GetFiveAccountsForClientByIdAsync(currentPage, clientId);

            var totalPages = await accountServices.GetPageCountForAccountsAsync(5, clientId);

            var fiveMappedAccounts = accountMapper.MapFrom(fiveAccountsDtos);

            var defaultAccountBalance = configuration.GetSection("DefaultAccountAmount").Value;

            var fiveAccounts = new FiveAccountsViewModel()
            {
                CurrPage = currentPage,
                TotalPages = totalPages,
                FiveAccountsList = fiveMappedAccounts,
                ClientId = clientId
            };

            var viewModel = new ManageClientAccountsViewModel()
            {
                ClientId = clientId,
                FiveAccountsList = fiveAccounts,
                DefaultAccountBalance = defaultAccountBalance
            };

            if (totalPages > currentPage)
            {
                fiveAccounts.NextPage = currentPage + 1;
            }

            if (currentPage > 1)
            {
                fiveAccounts.PrevPage = currentPage - 1;
            }

            return PartialView("_AccountsManagePartial", viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> GetFiveAccountsForClientById(int? currPage, long clientId)
        {
           if (!ModelState.IsValid)
           {
               return BadRequest();
           }

           var currentPage = currPage ?? 1;

           var totalPages = await accountServices.GetPageCountForAccountsAsync(5, clientId);
           var fiveAccForClientsById = await accountServices.GetFiveAccountsForClientByIdAsync(currentPage, clientId);
           var mappedFiveAccForClientsById = accountMapper.MapFrom(fiveAccForClientsById);


           var viewModel = new FiveAccountsViewModel()
           {
               CurrPage = currentPage,
               TotalPages = totalPages,
               FiveAccountsList = mappedFiveAccForClientsById,
               ClientId = clientId
           };

           if (totalPages > currentPage)
           {
               viewModel.NextPage = currentPage + 1;
           }

           if (currentPage > 1)
           {
               viewModel.PrevPage = currentPage - 1;
           }

           return PartialView("_AccountsListTable", viewModel);            
        }

        [HttpGet]
        public async Task<IActionResult> ManageClient(long clientId)
        {
           var currentPage = 1;

           var fiveAccountsDtos = await accountServices.GetFiveAccountsForClientByIdAsync(1, clientId);

           var fiveMappedAccounts = accountMapper.MapFrom(fiveAccountsDtos);

           var clientDto = await clientServices.GetClientByIdAsync(clientId);

           var clientViewModel = clientMapper.MapFrom(clientDto);

           var totalPages = await accountServices.GetPageCountForAccountsAsync(5, clientId);

            var defaultAccountBalance = configuration.GetSection("DefaultAccountAmount").Value;

            var fiveAccounts = new FiveAccountsViewModel()
           {
               CurrPage = currentPage,
               TotalPages = totalPages,
               FiveAccountsList = fiveMappedAccounts,
               ClientId = clientViewModel.Id
           };

           if (totalPages > currentPage)
           {
               fiveAccounts.NextPage = currentPage + 1;
           }

           if (totalPages > 1)
           {
               fiveAccounts.NextPage = currentPage + 1;
           }

           if (currentPage > 1)
           {
               fiveAccounts.PrevPage = currentPage - 1;
           }

           var manageClientViewModel = new ManageClientAccountsViewModel()
           {
               ClientId = clientViewModel.Id,
               FiveAccountsList = fiveAccounts,
               DefaultAccountBalance = defaultAccountBalance
           };

           var viewModel = new ManageClientViewModel()
           {
               ClientToManage = clientViewModel,
               ManageClientAccounts = manageClientViewModel
           };

           return View(viewModel);          
        }

        [HttpGet]
        public async Task<IActionResult> ManageUsersForClient(long clientId)
        {
            var currentPage = 1;

            var fiveUsersDtos = await userServices.GetFiveUsersForClientByIdAsync(currentPage, clientId);

            var totalPages = await userServices.GetPageCountForUsersWithClientIdAsync(5, clientId);

            var fiveMappedUsers = userMapper.MapFrom(fiveUsersDtos);

            var fiveUsers = new FiveUsersViewModel()
            {
                CurrPage = currentPage,
                TotalPages = totalPages,
                FiveUsersList = fiveMappedUsers,
                ClientId = clientId
            };

            var viewModel = new ManageClientUsersViewModel()
            {
                ClientId = clientId,

                FiveUsersList = fiveUsers
            };

            if (totalPages > 1)
            {
                fiveUsers.NextPage = currentPage + 1;
            }

            if (currentPage > 1)
            {
                fiveUsers.PrevPage = currentPage - 1;
            }

            return PartialView("_UsersManagePartial", viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> GetFiveUsersForClientById(int? currPage, long clientId)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var currentPage = currPage ?? 1;

Transact/Transact.Web/Areas/Admin/Views/Client/AddClient.cshtml
@model AddClientsViewModel
@{
    ViewData["Title"] = "Add Client";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutCustom.cshtml";
}

<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-lg-7 main-content">
                <div class="card content-area">
                    <div class="card-innr">
                        <div class="card-head">
                            <h4 class="card-title">All Clients</h4>
                        </div>
                        <span id="target-client-list-table">
                            @await Html.PartialAsync("_ClientListTable", Model.ClientsList)
                        </span>
                    </div><!-- .card-innr -->
                </div><!-- .card -->
            </div><!-- .content -->

            <!--add user -->
            <div class="col-md-5 aside sidebar-right ">
                <div class="card card-navs">
                    <div class="card-innr">
                        <div class="card-head d-lg-block">
                            <h6 class="card-title card-title-md">Add New Client</h6>
                        </div>
                        <form id="submit-client-form"  asp-controller="Client" asp-action="SaveClient">
                            <div class="col-md-13">
                                <div class="input-item input-with-label">
                                    <label class="input-item-label">Name</label>
                                    <input asp-for="ClientForm.Name" class="input-bordered" type="text" placeholder="Must be between 3 and 35 characters">
                                    <span asp-validation-for="ClientForm.Name" class="text-danger"></span>
                                </div>
                                <div class="input-item input-with-label">
                                    <label class="pdb-0-5x">If added correctly it will appear on your left!</label>
                                    <button type="submit" href="#" class="btn btn-primary btn-block" id="add-client-button">Click to Add</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <!--end add user -->
        </div><!-- .row -->
    </div><!-- .container -->
</div><!-- .page-content -->

@section Scripts{

    <script src="~/js/manage-clients-add-form.js"></script>
    <script src="~/js/manage-clients-pagination-table-buttons.js"></script>
}

Transact/Transact.Web/Areas/Admin/Views/Client/ManageClient.cshtml
@model ManageClientViewModel
@{
    ViewData["Title"] = "Manage Client Page";
    Layout = "~/Areas/Admin/Views/Shared/_LayoutCustom.cshtml";
}

<link href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/jquery-autocomplete/1.0.7/jquery.auto-complete.css" rel="stylesheet" />
<link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
<link href="~/css/transaction-select2-style.css" rel="stylesheet" />

<div class="page-content">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 aside sidebar-left">
                <div class="card card-navs">
                    <div class="card-innr">
                        <div class="card-head d-none d-lg-block">
                            <h6 class="card-title card-title-md">Client: @Model.ClientToManage.Name</h6>
                        </div>
                        <ul class="sidebar-nav">
                            <li><a href="#" id="toggle-account-management-button" clientId="@Model.ClientToManage.Id"><em class="ikon ikon-exchange"></em> Manage Accounts</a></li>
                            <li><a href="#" id="toggle-user-management-button" clientId="@Model.ClientToManage.Id"><em class="ikon ikon-user"></em> Manage Users</a></li>
                        </ul>
                    </div>
                </div>
                <div class="pb-3">
                    <a asp-area="Admin" asp-controller="Client" asp-action="AddClient" class="btn btn-lg btn-light-alt"><em class="fas fa-arrow-left mr-3"></em>Back to Client Management</a>
                </div>
            </div>
            <div class="col-lg-9 main-content" id="client-manage-holder">
                @await Html.PartialAsync("_AccountsManagePartial", Model.ManageClientAccounts)
            </div>
        </div>
    </div><!-- .container -->
</div><!-- .page-content -->

@section Scripts{
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
            integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
            crossorigin="anonymous"></script>

    <script src="~/js/manage-accountsForClients-pagination-table-buttons.js"></script>
    <script src="~/js/remove-user-from-client.js"></script>

    <script src="~/js/manage-clientUsers-add-form.js"></script>
    <script src="~/js/manage-accounts-add-form.js"></script>
    <script src="~/js/client-holder-management.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-autocomplete/1.0.7/jquery.auto-complete.min.js"></script>
}