Transact/Transact.Web/Areas/Admin/Controllers/DashboardController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Transact.Models.Dtos;
using Transact.Services.Contracts;
using Transact.Web.Areas.Admin.ViewModels;
using Transact.Web.Mapper.Contracts;
using Transact.Web.Utills;

namespace Transact.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [CustomAuthorize("Admin")]
    public class DashboardController : Controller
    {
        private readonly IUserServices userServices;
        private readonly IClientServices clientServices;
        private readonly IUserViewModelMapper userVieModelMapper;
        private readonly IClientViewModelMapper clientViewModelMapper;
        private readonly IMemoryCache memoryCache;

        public DashboardController(
            IUserServices userServices, 
            IClientServices clientServices,
            IUserViewModelMapper userVieModelMapper,
            IClientViewModelMapper clientViewModelMapper,
            IMemoryCache memoryCache)
        {
            this.userServices = userServices;
            this.clientServices = clientServices;
            this.userVieModelMapper = userVieModelMapper;
            this.clientViewModelMapper = clientViewModelMapper;
            this.memoryCache = memoryCache;
        }

        public async Task<IActionResult> Index()
        {
            var totalUsers = await userServices.GetTotalUsersCountAsync();           

            var cachedLatestUsers = await memoryCache.GetOrCreateAsync<IList<UserDto>>("LatestFiveUsers", async (cacheEntry) =>
            {
                var cachedUsers = await userServices.GetFiveUsersByIdAsync(1);
                cacheEntry.SlidingExpiration = TimeSpan.FromHours(1);
                return cachedUsers;
            });

            var cachedLatestClients = await memoryCache.GetOrCreateAsync<ICollection<ClientDto>>("LatestSevenClients", async (cacheEntry) =>
            {
                var cachedClients = await clientServices.GetSevenLatestClientsAsync();
                cacheEntry.SlidingExpiration = TimeSpan.FromHours(1);
                return cachedClients;
            });

            var fiveMappedUsers = userVieModelMapper.MapFrom(cachedLatestUsers);
            var sevenMappedClients = clientViewModelMapper.MapFrom(cachedLatestClients);

            var viewModel = new AdminDashViewModel()
            {
                TotalUsers = totalUsers,
                SevenLatestClients = sevenMappedClients,
                FiveLatestUsers = fiveMappedUsers
            };

            return View(viewModel);
        }

        public async Task<IActionResult> About()
        {            
            return View();
        }
    }
}

Transact/Transact.Web/Areas/Admin/Controllers/IdentityController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Transact.Services.Contracts;
using Transact.Web.Areas.Admin.ViewModels;

namespace Transact.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [AllowAnonymous]
    public class IdentityController : Controller
    {
        private readonly ITokenManager tokenManager;
        private readonly IAdminServices adminServices;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly ICookieManager cookieManager;

        public IdentityController(
            IAdminServices adminServices,
            ITokenManager tokenManager,
            IHttpContextAccessor httpContextAccessor,
            ICookieManager cookieManager)
        {
            this.adminServices = adminServices;
            this.tokenManager = tokenManager;
            this.httpContextAccessor = httpContextAccessor;
            this.cookieManager = cookieManager;
        }

        [HttpPost]
        [AllowAnonymous]
        public async Task<IActionResult> Login(AdminLoginViewModel adminModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("Please enter valid login form!");
            }

            var admin = await adminServices.GetAdminAsync(adminModel.UserName, adminModel.Password);

            var token = tokenManager.GenerateToken(admin.UserName, admin.RoleName, admin.Id.ToString());

            cookieManager.AddSessionCookieForToken(token, admin.UserName);

            return Ok("Successfully logged in!");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            cookieManager.DeleteSessionCookies();

            return Ok("Succesfully logged out!");
        }
    }
}

Transact/Transact.Web/Areas/AppUser/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Transact.Services.Contracts;
using Transact.Web.Areas.AppUser.ViewModels;
using Transact.Web.Mapper.Contracts;

namespace Transact.Web.Areas.AppUser.Controllers
{
    [Area("AppUser")]
    [AllowAnonymous]
    public class DashboardController : Controller
    {
        private readonly IBannerServices bannerServices;
        private readonly IBannerViewModelMapper bannerViewModelMapper;

        public DashboardController(IBannerServices bannerServices, IBannerViewModelMapper bannerViewModelMapper)
        {
            this.bannerServices = bannerServices;
            this.bannerViewModelMapper = bannerViewModelMapper;
        }

        [HttpGet]
        public async Task<IActionResult> LoginPage()
        {
            var allActiveBanners = await bannerServices.GetActiveBannersImagePathsAsync(DateTime.Now);

            var allActiveBannersViewModeList = bannerViewModelMapper.MapFrom(allActiveBanners);

            var viewModel = new LoginViewModel()
            {
                ActiveBanners = allActiveBannersViewModeList
            };            

            return View("LoginMain", viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> About()
        {
            return View();
        }
    }
}

Transact/Transact.Web/Areas/AppUser/Views/Dashboard/LoginMain.cshtml
@model Transact.Web.Areas.AppUser.ViewModels.LoginViewModel

<!DOCTYPE html>
<html lang="zxx" class="js">
<head>
    <meta charset="utf-8">
    <meta name="author" content="Softnio">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Fully featured and complete ICO Dashboard template for ICO backend management.">
    <!-- Fav Icon  -->
    <link rel="shortcut icon" href="/images/favicon.png">
    <!-- Site Title  -->
    <title>Transact - User Login</title>
    <!-- Vendor Bundle CSS -->
    <link rel="stylesheet" href="/assets/css/vendor.bundle.css?ver=104">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="/assets/css/style.css?ver=104">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.css" />

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />

</head>
<body class="page-ath">

    <div class="page-ath-wrap">

        <div class="page-ath-gfx">
            <div class="w-100 ">
                <div class="single-image-banner">
                    @foreach (var image in Model.ActiveBanners)
                    {
                        <a href="#" onclick="window.open('@image.Url')"><img href="@image.Url" src="@image.ImagePath"></a>
                    }

                </div>
            </div>
        </div>
        <div class="page-ath-content">
            <div class="page-ath-header">
                <a asp-controller="Home" asp-action="Index" class="page-ath-logo"><img src="/images/logo.png" srcset="/images/logo2x.png 2x" alt="logo"></a>
            </div>
            <div class="page-ath-form">
                <h2 class="page-ath-heading">Sign in <small>with your Transact Account</small></h2>
                <form asp-controller="Identity" asp-action="Login" method="post" redirectPath="/AppUser/Account/AccountDash" id="login-form">
                    <div class="input-item">
                        <input asp-for="UserName" type="text" value="DemoUser" placeholder="Your Username" class="input-bordered">
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                    <div class="input-item">
                        <input asp-for="Password" type="password" value="DemoP@ssw0rd" placeholder="Password" class="input-bordered">
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <button class="btn btn-primary btn-block">Sign In</button>
                </form>
            </div>
            <div class="page-ath-footer">
                <ul class="footer-links">
                    <li><a href="#">Privacy Policy</a></li>
                    <li><a href="#">Terms</a></li>
                    <li>&copy; 2019 Transact</li>
                </ul>
            </div>
        </div>
    </div>

    <!-- JavaScript (include all script here) -->
    <script src="/assets/js/jquery.bundle.js?ver=104"></script>
    <script src="/assets/js/script.js?ver=104"></script>

    <script src="https://code.jquery.com/jquery-2.2.4.js"
            integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
            crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.2/jquery.validate.unobtrusive.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.9.0/slick.min.js"></script>

    <script src="~/js/appuser-login-banner-rotation-slickVersion.js"></script>

    <script src="~/js/login-submission.js"></script>
</body>
</html>