Transact/Transact.Web/Areas/Admin/ViewModels/ClientListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Transact.Web.Areas.Admin.ViewModels
{
    public class ClientListViewModel
    {
        public int? PrevPage { get; set; }

        public int CurrPage { get; set; }

        public int? NextPage { get; set; }

        public int TotalPages { get; set; }

        public IList<ClientViewModel> FiveClientsById { get; set; }
    }
}

Transact/Transact.Web/Areas/Admin/ViewModels/UserListViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Transact.Web.Areas.Admin.ViewModels
{
    public class UserListViewModel
    {
        public int? PrevPage { get; set; }

        public int CurrPage { get; set; }       

        public int? NextPage { get; set; }

        public int TotalPages { get; set; }

        public IList<UserViewModel> FiveUsersById { get; set; }
    }
}

Transact/Transact.Web/Areas/Admin/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Transact.FileManager.Contracts;
using Transact.Services.Contracts;
using Transact.Web.Areas.Admin.ViewModels;
using Transact.Web.Mapper.Contracts;
using Transact.Web.Utills;

namespace Transact.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [CustomAuthorize("Admin")]
    public class BannerController : Controller
    {
        private readonly IBannerServices bannerServices;
        private readonly IBannerViewModelMapper bannerViewModelMapper;
        private readonly ILocalStorageManager localStorageManager;

        public BannerController
            (IBannerServices bannerServices,
             IBannerViewModelMapper bannerViewModelMapper,
             ILocalStorageManager localStorageManager)
        {
            this.bannerServices = bannerServices;
            this.bannerViewModelMapper = bannerViewModelMapper;
            this.localStorageManager = localStorageManager;
        }

        public IActionResult ManageBanners()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> AddBanner()
        {
            var fiveBannerDtos = await bannerServices.GetFiveBannersByExpirationDateAsync();

            var totalPages = await bannerServices.GetPageCountForBanersAsync(5);

            var fiveMappedBanners = bannerViewModelMapper.MapFrom(fiveBannerDtos);

            var viewModel = new BannerManagementViewModel()
            {
                FiveBanners = new FiveBannersViewModel()
                {
                    FiveBannersList = fiveMappedBanners,
                    CurrPage = 1,
                    TotalPages = totalPages                    
                },
                BannerForm = new BannerViewModel()
            };

            if (totalPages > 1)
            {
                viewModel.FiveBanners.NextPage = viewModel.FiveBanners.CurrPage + 1;
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> GetFiveBanners(int? currPage)
        {
            currPage = currPage ?? 1;

            var fiveBannerDtos = await bannerServices.GetFiveBannersByExpirationDateAsync((int)currPage);

            var totalPages = await bannerServices.GetPageCountForBanersAsync(5);

            var fiveMappedBanners = bannerViewModelMapper.MapFrom(fiveBannerDtos);

            var viewModel = new FiveBannersViewModel()
            {
                FiveBannersList = fiveMappedBanners,
                CurrPage = (int)currPage,
                TotalPages = totalPages
            };

            if (totalPages > currPage)
            {
                viewModel.NextPage = currPage + 1;
            }

            if (currPage > 1)
            {
                viewModel.PrevPage = currPage - 1;
            }

            return PartialView("_BannerListTable", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SaveBanner(BannerViewModel bannerToSave)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("Please enter valid form!");
            }

            var bannerDtoToSave = bannerViewModelMapper.MapFrom(bannerToSave);

            var imageName = await localStorageManager.SaveFileAsync(bannerToSave.Image);

            bannerDtoToSave.ImageName = imageName;

            var savedBannerDto = await bannerServices.SaveBannerAsync(bannerDtoToSave);

            return Ok("Banner succesfuly added!");

        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateBanner(EditBannerViewModel bannerToUpdate)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("Please enter valid form!");
            }

            var bannerDtoToEdit = bannerViewModelMapper.MapFromForEditing(bannerToUpdate);

            if (bannerToUpdate.IsNewImage)
            {
                var newImageName = await localStorageManager.SaveFileAsync(bannerToUpdate.Image);

                bannerDtoToEdit.ImageName = newImageName;

                var oldImageName = bannerToUpdate.ImageName;

                localStorageManager.DeleteFile(oldImageName);
            }                     

            var editedBannerDto = await bannerServices.UpdateBannerAsync(bannerDtoToEdit);

            return Ok("Banner succesfuly edited!");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditBanner(long id)
        {
            var bannerToEdit = await bannerServices.GetSingleBannerForEditingAsync(id);

            var viewModel = bannerViewModelMapper.MapFromForEditing(bannerToEdit);

            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteBanner(long id)
        {
            var bannerToDelete = await bannerServices.DeleteBannerAsync(id);

            return Ok("Banner succesfuly deleted!");
        }      
    }
}

Transact/Transact.Web/Areas/Admin/Controllers/UserController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Transact.Services.Contracts;
using Transact.Web.Areas.Admin.ViewModels;
using Transact.Web.Mapper.Contracts;
using Transact.Web.Utills;

namespace Transact.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [CustomAuthorize("Admin")]
    public class UserController : Controller
    {
        private readonly IUserServices userServices;
        private readonly IUserViewModelMapper userMapper;
        private readonly IHttpContextAccessor httpContextAccessor;
        private readonly IAccountServices accountServices;
        private readonly IAccountViewModelMapper accountMapper;

        public UserController(
            IUserServices userServices,
            IUserViewModelMapper userMapper,
            IHttpContextAccessor httpContextAccessor,
            IAccountServices accountServices,
            IAccountViewModelMapper accountMapper)
        {
            this.userServices = userServices;
            this.userMapper = userMapper;
            this.httpContextAccessor = httpContextAccessor;
            this.accountServices = accountServices;
            this.accountMapper = accountMapper;
        }


        [HttpGet]
        public async Task<IActionResult> AddUser()
        {
            var fiveUsersById = await userServices.GetFiveUsersByIdAsync(1);
            var mappedFiveUsersById = userMapper.MapFrom(fiveUsersById);
            var totalPages = await userServices.GetPageCountForUsersAsync(5);

            var viewModel = new AddUserViewModel()
            {
                UserForm = new UserViewModel(),
                UsersList = new UserListViewModel()
                {
                    CurrPage = 1,
                    TotalPages = totalPages,
                    FiveUsersById = mappedFiveUsersById
                }
            };

            if (totalPages > 1)
            {
                viewModel.UsersList.NextPage = 2;
            }

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> GetFiveUsersById(int? currPage)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var currentPage = currPage ?? 1;

            var totalPages = await userServices.GetPageCountForUsersAsync(5);
            var fiveUsersById = await userServices.GetFiveUsersByIdAsync(currentPage);
            var mappedFiveUsersById = userMapper.MapFrom(fiveUsersById);


            var viewModel = new UserListViewModel()
            {
                CurrPage = currentPage,
                TotalPages = totalPages,
                FiveUsersById = mappedFiveUsersById
            };

            if (totalPages > currentPage)
            {
                viewModel.NextPage = currentPage + 1;
            }

            if (currentPage > 1)
            {
                viewModel.PrevPage = currentPage - 1;
            }

            return PartialView("_UserListTable", viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> SaveUser(AddUserViewModel manageViewModel)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest("Please submit valid form!");
            }

            var userDto = userMapper.MapFrom(manageViewModel.UserForm);

            var user = await userServices.
                AddUserAsync(userDto);

            return Ok($"User with Username: \"{user.UserName}\" addedd succesfully!");
        }

        [HttpPost]
        public async Task<JsonResult> FindSingleByUserName(string userNameString, long clientId)
        {
            if (string.IsNullOrEmpty(userNameString))
            {
                return Json(string.Empty);
            }

            var allUsersContaining = await userServices.FindUsersContainingAsync(userNameString, clientId);

            var allUsersModels = userMapper.MapFrom(allUsersContaining);

            return Json(allUsersModels);
        }

        [HttpGet]
        public async Task<IActionResult> ManageUser(long userId)
        {
            var currentPage = 1;

            var fiveAccountsDtos = await accountServices.GetFiveAccountsForUserByIdAsync(currentPage, userId);

            var fiveMappedAccounts = accountMapper.MapFrom(fiveAccountsDtos);

            var userDto = await userServices.GetUserByIdAsync(userId);
            var userViewModel = userMapper.MapFrom(userDto);

            var totalPages = await accountServices.GetPageCountForAccountsWithUsersIdAsync(5, userId);


            var fiveAccounts = new FiveAccountsViewModel()
            {
                CurrPage = currentPage,
                TotalPages = totalPages,
                FiveAccountsList = fiveMappedAccounts,
                UserId = userViewModel.Id
            };

            if (totalPages > currentPage)
            {
                fiveAccounts.NextPage = currentPage + 1;
            }

            if (totalPages > 1)
            {
                fiveAccounts.NextPage = currentPage + 1;
            }

            if (currentPage > 1)
            {
                fiveAccounts.PrevPage = currentPage - 1;
            }

            var manageUserViewModel = new ManageUserAccountsViewModel()
            {
                UserId = userViewModel.Id,
                FiveAccountsList = fiveAccounts
            };

            var viewModel = new ManageUserViewModel()
            {
                UserToManage = userViewModel,
                ManageUserAccounts = manageUserViewModel
            };

            return View(viewModel);
        }

        [HttpGet]
        public async Task<IActionResult> GetFiveAccountsForUserById(int? currPage, long userId)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var currentPage = currPage ?? 1;

            var totalPages = await accountServices.GetPageCountForAccountsWithUsersIdAsync(5, userId);
            var fiveAccountsForUsersById = await accountServices.GetFiveAccountsForUserByIdAsync(currentPage, userId);
            var mappedFiveAccountsForUsersById = accountMapper.MapFrom(fiveAccountsForUsersById);


            var viewModel = new FiveAccountsViewModel()
            {
                CurrPage = currentPage,
                TotalPages = totalPages,
                FiveAccountsList = mappedFiveAccountsForUsersById,
                UserId = userId
            };

            if (totalPages > currentPage)
            {
                viewModel.NextPage = currentPage + 1;
            }

            if (currentPage > 1)
            {
                viewModel.PrevPage = currentPage - 1;
            }

            return PartialView("_UserAccountsListTable", viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AssignAccountToUser(string AccountNumber, long userId)
        {
            var account = await accountServices.AssignAccountToUserAsync(AccountNumber, userId);

            return Ok($"User with name: \"{account.AccountNumber}\" assigned succesfully!");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> RemoveUserForClient(long userId, long accountId)
        {
            var account = await accountServices.RemoveAccountForUser(userId, accountId);

            return Ok($"Account \"{account}\" removed from user!");
        }

        [HttpPost]
        public async Task<JsonResult> FindSingleByAccountNumberForUser(string accountNumberString, long userId)
        {
            if (string.IsNullOrEmpty(accountNumberString))
            {
                return Json(string.Empty);
            }

            var allAccountsContaining = await accountServices.FindAccountsForUserContainingAsync(accountNumberString, userId);

            var allAccontsModels = accountMapper.MapFrom(allAccountsContaining);

            return Json(allAccontsModels);
        }
    }
}

Transact/Transact.Web/Areas/Admin/Views/Shared/_AccountsListTable.cshtml
@model FiveAccountsViewModel

<table class="mobile-transact-table-scroll data-table account-list" id="account-table-list-by-id">
    <thead>
        <tr class="data-item data-head">
            <th class="data-col dt-user">Account/Id</th>
            <th class="data-col dt-user">Nickname</th>
            <th class="data-col dt-user">Balance</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var account in Model.FiveAccountsList)
        {
            <tr class="data-item">
                <td class="data-col dt-account">
                    <span class="lead account-name">@account.AccountNumber</span>
                    <span class="sub account-id">Id: #@account.Id</span>
                </td>
                <td class="data-col dt-account">
                    <span class="lead account-name">@account.NickName</span>
                </td>
                <td class="data-col dt-account">
                    <span class="lead account-name">@account.Balance</span>
                </td>
            </tr><!-- .data-item -->
        }
    </tbody>
</table>

@if (Model.PrevPage == null)
{
    <a class="btn btn-sm btn-lighter btn-auto disabled">Prev</a>
}
else
{
    <a class="btn btn-sm btn-lighter btn-auto pagination-account-table-button" at="@Model.PrevPage">Prev</a>
    <a class="btn btn-sm btn-lighter btn-auto pagination-account-table-button" at="@Model.PrevPage">@Model.PrevPage</a>
}

<button class="btn btn-sm btn-primary btn-auto">@Model.CurrPage</button>

@if (Model.NextPage == null)
{
    <a class="btn btn-sm btn-lighter btn-auto disabled">Next</a>
}
else
{
    <a class="btn btn-sm btn-lighter btn-auto pagination-account-table-button" at="@Model.NextPage">@Model.NextPage</a>
    <a class="btn btn-sm btn-lighter btn-auto pagination-account-table-button" at="@Model.NextPage">Next</a>
}

Transact/Transact.Web/Areas/Admin/Views/Shared/_AccountsManagePartial.cshtml
@model ManageClientAccountsViewModel
@{
    ViewData["Title"] = "_AccountsManagePartial";
}

<div class="card content-area">
    <div class="card-innr">
        <div class="card-head">
            <h6 class="card-title">Add new Account</h6>
        </div>
        <div class="gaps-1x"></div><!-- .gaps -->
        <form id="submit-account-form" asp-area="Admin" asp-controller="Account" asp-action="CreateAccount" class="row">
            <div class="col-md-6">
                <div class="input-item input-with-label">
                    <label class="input-item-label">Initial Balance</label>
                    <input asp-for="Balance" class="input-bordered" type="number" value="@Model.DefaultAccountBalance">
                    <span asp-validation-for="Balance" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <input asp-for="ClientId" id="client-id-input-hidden" type="hidden" name="ClientId" value="@Model.ClientId" />
                <div class="input-item input-with-label">
                    <label class="input-item-label">If added correctly it will appear bottom!</label>
                    <button type="submit" href="#" class="btn btn-primary btn-block" id="add-account-button">Click to Create Account</button>
                </div>
            </div>
        </form>
    </div><!-- .card-innr -->
</div><!-- .card -->

<div class="card content-area">
    <div class="card-innr" id="target-account-list-table">
        @await Html.PartialAsync("_AccountsListTable", Model.FiveAccountsList)
    </div><!-- .card-innr -->
</div><!-- .card -->

Transact/Transact.Web/Areas/Admin/Views/Shared/_BannerListTable.cshtml
@model FiveBannersViewModel
<table class="data-table user-list mobile-transact-table-scroll" id="user-table-list-by-id">
    @if (Model.FiveBannersList.Count > 0)
    {
        <thead>
            <tr class="data-item data-head">          
                <th class="data-col ">Image</th>
                <th class="data-col ">Banner Url Link</th>
                <th class="data-col ">Start / End Date</th>
                <th class="data-col"></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var banner in Model.FiveBannersList)
            {
                <tr class="data-item">
                    <td class="data-col" style="width: 15%;">
                        <img src="@banner.ImagePath" />                   
                    </td>
                    <td class="data-col">
                        <a class="sub" href="@banner.Url">@banner.Url</a>
                    </td>

                    <td class="data-col">
                        <span class="lead sub-time">@banner.StartDate.ToString("dd MMM yyyy", System.Globalization.CultureInfo.InvariantCulture)</span>
                        <span class="sub sub-s2 sub-time">@banner.EndDate.ToString("dd MMM yyyy", System.Globalization.CultureInfo.InvariantCulture)</span>
                    </td>
                    <td class="data-col text-right">
                        <div class="relative d-inline-block">
                            <a href="#" class="btn btn-light-alt btn-xs btn-icon toggle-tigger"><em class="ti ti-more-alt"></em></a>
                            <div class="toggle-class dropdown-content dropdown-content-top-left">
                                <ul class="dropdown-list">
                                    <li><form method="post"><button class="editButton btn btn-auto" type="submit" asp-route-id="@banner.Id" asp-area="Admin" asp-controller="Banner" asp-action="EditBanner"><em class="ti ti-list"> &nbsp; </em>Edit</button></form></li>
                                    <li><a href="#" id="delete-banner-button-@banner.Id" bannerId="@banner.Id" class="banner-delete-button-class"><em class="ti ti-trash"></em>Delete</a></li>
                                </ul>
                            </div>
                        </div>
                    </td>
                </tr><!-- .data-item -->
            }
        </tbody>    
    }
</table>

<span id="anti-forgery-token-banners">@Html.AntiForgeryToken()</span>

@if (Model.FiveBannersList.Count == 0)
{
    <div class="card-body">
        <h3>No banners in the app yet! We gotta work on that sponsors list, boss!</h3>
    </div>
}
else
{
    @if (Model.PrevPage == null)
    {
        <a class="btn btn-sm btn-lighter btn-auto disabled">Prev</a>
    }
    else
    {
        <a class="btn btn-sm btn-lighter btn-auto banner-pagination-buttons" at="@Model.PrevPage">Prev</a>
        <a class="btn btn-sm btn-lighter btn-auto banner-pagination-buttons" at="@Model.PrevPage">@Model.PrevPage</a>
    }

    <button class="btn btn-sm btn-primary btn-auto">@Model.CurrPage</button>

    @if (Model.NextPage == null)
    {
        <a class="btn btn-sm btn-lighter btn-auto disabled">Next</a>
    }
    else
    {
        <a class="btn btn-sm btn-lighter btn-auto banner-pagination-buttons" at="@Model.NextPage">@Model.NextPage</a>
        <a class="btn btn-sm btn-lighter btn-auto banner-pagination-buttons" at="@Model.NextPage">Next</a>
    }
}

Transact/Transact.Web/Areas/Admin/Views/Shared/_LayoutCustom.cshtml
<!DOCTYPE html>
<html lang="zxx" class="js">
<head>
    <meta charset="utf-8">
    <meta name="author" content="Softnio">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Fully featured and complete ICO Dashboard template for ICO backend management.">
    <!-- Fav Icon  -->
    <link rel="shortcut icon" href="/images/favicon.png">
    <!-- Site Title  -->
    <title>TokenWiz - ICO User Dashboard Admin Template</title>
    <!-- Vendor Bundle CSS -->
    <link rel="stylesheet" href="/assets/css/vendor.bundle.css?ver=104">
    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="/assets/css/style.css?ver=104">
    <!-- Custom App added style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css" />
    
    <link rel="stylesheet" href="~/css/mobile-table-side-scroll.css" />
</head>
<body class="page-user">
    <div class="topbar-wrap">
        <div class="topbar is-sticky">
            <div class="container">
                <div class="d-flex justify-content-between align-items-center">
                    <ul class="topbar-nav d-lg-none">
                        <li class="topbar-nav-item relative">
                            <a class="toggle-nav" href="#">
                                <div class="toggle-icon">
                                    <span class="toggle-line"></span>
                                    <span class="toggle-line"></span>
                                    <span class="toggle-line"></span>
                                    <span class="toggle-line"></span>
                                </div>
                            </a>
                        </li><!-- .topbar-nav-item -->
                    </ul><!-- .topbar-nav -->
                    <a class="topbar-logo" asp-area="Admin" asp-controller="Dashboard" asp-action="Index">
                        <img src="/images/logo-light2x.png" srcset="/images/logo-light2x.png 2x" alt="logo">
                    </a>
                    <ul class="topbar-nav">
                        <li class="topbar-nav-item relative">
                            <span class="user-welcome d-none d-lg-inline-block">Welcome! @Context.Request.Cookies["LoginInfo"]</span>
                            <a class="toggle-tigger user-thumb" href="#"><em class="ti ti-user"></em></a>
                            <div class="toggle-class dropdown-content dropdown-content-right dropdown-arrow-right user-dropdown">
                                <ul class="user-links bg-light">
                                    <li><form method="post" id="logout-form-admin-general" logoutHref="/Home/Index"><a href="#" id="logout-form-admin-link"><i class="ti ti-power-off"></i>Logout</a></form></li>
                                </ul>
                            </div>
                        </li><!-- .topbar-nav-item -->
                    </ul><!-- .topbar-nav -->
                </div>
            </div><!-- .container -->
        </div><!-- .topbar -->
        <div class="navbar">
            <div class="container">
                <div class="navbar-innr">
                    <ul class="navbar-menu">
                        <li><a asp-area="Admin" asp-controller="Dashboard" asp-action="Index"><em class="ikon ikon-dashboard"></em> Dashboard</a></li>
                        <li><a asp-area="Admin" asp-controller="User" asp-action="AddUser"><em class="ikon ikon-user"></em> Manage Users</a></li>
                        <li><a asp-area="Admin" asp-controller="Client" asp-action="AddClient"><em class="ikon ikon-wallet"></em>Manage Clients / Accounts</a></li>
                        <li><a asp-area="Admin" asp-controller="Banner" asp-action="AddBanner"><em class="ikon ikon-exchange"></em> Manage Banners</a></li>
                    </ul>
                    <ul class="navbar-btns">
                        <li><a asp-controller="Home" asp-action="Index" class="btn btn-sm btn-outline btn-light"><em class="text-primary ti ti-home"></em><span>Back to Website Home</span></a></li>
                    </ul>
                </div><!-- .navbar-innr -->
            </div><!-- .container -->
        </div><!-- .navbar -->
    </div><!-- .topbar-wrap -->

    <div class="page-content">
        <div class="container">
            <!-- START OF PAGE BODY -->
            @RenderBody()
            <!-- END OF PAGE BODY -->
        </div><!-- .container -->
    </div><!-- .page-content -->

    <div class="footer-bar">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-md-8">
                    <ul class="footer-links">
                        <li><a asp-controller="Home" asp-action="Index">Back to Home</a></li>
                        <li><a asp-area="Admin" asp-controller="Dashboard" asp-action="About">About the project</a></li>
                    </ul>
                </div><!-- .col -->
                <div class="col-md-4 mt-2 mt-sm-0">
                    <div class="d-flex justify-content-between justify-content-md-end align-items-center guttar-25px pdt-0-5x pdb-0-5x">
                        <div class="copyright-text">&copy; 2018 Transact</div>
                    </div>
                </div><!-- .col -->
            </div><!-- .row -->
        </div><!-- .container -->
    </div><!-- .footer-bar -->
    <!-- JavaScript (include all script here) -->
    <script src="/assets/js/jquery.bundle.js?ver=104"></script>
    <script src="/assets/js/script.js?ver=104"></script>
    <script src="/assets/js/toastr.examples.js?ver=104"></script>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
            integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo="
            crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>



    <script src="https://code.jquery.com/jquery-2.2.4.js"
            integrity="sha256-iT6Q9iMJYuQiMWNd9lDyBUStIq/8PuOW33aOqmvFpqI="
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.19.0/jquery.validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.2/jquery.validate.unobtrusive.js"></script>
    <script src="~/js/logout-admin.js"></script>



    @await RenderSectionAsync("Scripts", required: false);

</body>
</html>

Transact/Transact.Web/Areas/Admin/Views/Shared/_UserAccountsManagePartial.cshtml
@model ManageUserAccountsViewModel
@{
    ViewData["Title"] = "_UserAccountsManagePartial";
}

<div class="card content-area">
    <div class="card-innr">
        <div class="card-head">
            <h6 class="card-title">Assign existing Accounts</h6>
        </div>
        <div class="gaps-1x"></div><!-- .gaps -->
        <form id="assign-account-for-user-form" asp-controller="User" asp-action="AssignAccountToUser" class="row">
            <div class="col-md-6">
                <div class="input-item input-with-label">
                    <label class="input-item-label">Select existing Account</label>
                    <input asp-for="AccountNumber" class="input-bordered" id="input-for-userAccounts" type="text" placeholder="Live Search for Accounts" />
                    <span asp-validation-for="AccountNumber" id="message" class="text-danger"></span>
                </div>
            </div>
            <div class="col-md-6">
                <input asp-for="UserId" id="user-id-for-assigning-account-hidden" type="hidden" name="UserId" value="@Model.UserId" />
                <div class="input-item input-with-label">
                    <label class="input-item-label">If added correctly it will appear bottom!</label>
                    <button type="submit" href="#" class="btn btn-primary btn-block" id="assign-user-to-client-button">Click to Assign Account</button>
                </div>
            </div>
        </form>
    </div><!-- .card-innr -->
</div><!-- .card -->

<div class="card content-area">
    <div class="card-innr" id="userAccounts-list-table-holder">
        @await Html.PartialAsync("_UserAccountsListTable", Model.FiveAccountsList)
    </div><!-- .card-innr -->
</div><!-- .card -->